// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEJF0AsI1AdE9TbLavWzRHiks6aRsgQkY',
    appId: '1:43620702304:web:511dbbc9e94367fb718b05',
    messagingSenderId: '43620702304',
    projectId: 'week-13-app',
    authDomain: 'week-13-app.firebaseapp.com',
    storageBucket: 'week-13-app.firebasestorage.app',
    measurementId: 'G-BZZ3L4YT2Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzpqQorEKv7iR93ZIPQuY33WLxLkom_eM',
    appId: '1:43620702304:android:87e1880962670097718b05',
    messagingSenderId: '43620702304',
    projectId: 'week-13-app',
    storageBucket: 'week-13-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEZS76mo9eAw24QHeFIOT6G3j9KBJEr0g',
    appId: '1:43620702304:ios:2bd390c86bd242a4718b05',
    messagingSenderId: '43620702304',
    projectId: 'week-13-app',
    storageBucket: 'week-13-app.firebasestorage.app',
    iosBundleId: 'com.example.mobileInternshipTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEZS76mo9eAw24QHeFIOT6G3j9KBJEr0g',
    appId: '1:43620702304:ios:2bd390c86bd242a4718b05',
    messagingSenderId: '43620702304',
    projectId: 'week-13-app',
    storageBucket: 'week-13-app.firebasestorage.app',
    iosBundleId: 'com.example.mobileInternshipTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEJF0AsI1AdE9TbLavWzRHiks6aRsgQkY',
    appId: '1:43620702304:web:f3cef79e1e180c5f718b05',
    messagingSenderId: '43620702304',
    projectId: 'week-13-app',
    authDomain: 'week-13-app.firebaseapp.com',
    storageBucket: 'week-13-app.firebasestorage.app',
    measurementId: 'G-PW0SR699FG',
  );

}